### ISSUE TITLE
Во время загрузки или ошибки не удаётся закрыть приложение через "крестик"

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#112]

**Comment by chekoopa** [comment]
Да, там в бэкенде на закрытие `preventDefault`, и наиболее надёжный способ – добавить флажок «вызвано закрытие» и API для его снятия. При закрытии поднимаем флажок, при отображении модалки флажок снимаем. Если закрытие вызывается снова, а флажок поднят – сразу закрываем окно. Так сказать, аварийное закрытие.
