### ISSUE TITLE
Убрать кеширование индекса документации (добавить обновление?)

### ISSUE THREAD

**Issue by chekoopa** [kruzhok-team/lapki-client#121]
При разработке проявилась проблема: после обновления индекса документации остаётся старая версия. Отчасти это проблема сервера (кеширование штука тонкая), отчасти клиента. Есть предложение не кешировать индекс и запрашивать его как есть. 

Возможно, такая же участь ждёт виджет просмотра страниц (добавить кнопку обновления мимо кеша).

Ссылка в помощь: https://stackoverflow.com/questions/29246444/fetch-how-do-you-make-a-non-cached-request

**Comment by bryzZz** [comment]
@chekoopa {cache: "no-store"} не помогает
