### ISSUE TITLE
Добавление метки к любому компоненту ломает компиляцию

### ISSUE THREAD

**Issue by L140-beep** [kruzhok-team/lapki-client#148]
См. название. Предлагаю убрать label из parameters.

**Comment by chekoopa** [comment]
Вынужден поменять местами название и текст тикета, так как предложение убрать текст метки (`label`) из параметров некорректно и требует детализации. Формат Cyberiada-GraphML подразумевает, что информация о метке хранится  вместе с остальными параметрами в текстовом блоке, т.к. иного способа хранения параметров компонента не предусмотрено. 

Отсюда мы имеем один из двух вариантов решения:
 - доработать парсер на стороне клиента (перенос `label` из параметров в отдельное поле). 
 - отсеивать несодержательные для компиляции параметры на стороне компилятора. 

Считаю второй вариант более правильным с точки зрения архитектуры и трудоёмкости.

**Comment by chekoopa** [comment]
Исправлено со стороны компилятора в https://github.com/kruzhok-team/lapki-compiler/pull/19.
