### ISSUE TITLE
Редизайн модальных окон

### ISSUE THREAD

**Issue by XidFanSan** [kruzhok-team/lapki-client#149]
Требуется переписать как минимум createModal.tsx для лучшей читабельности и разделения кода для разных задач, потому что сейчас всё реализовано в одном файле.

**Comment by chekoopa** [comment]
Пожалуйста, добавь предположение о том, как именно нужно переписать CreateModal. 

Да, сейчас модалка одновременно отвечает за ноду и переход, но у них по факту много общего в логике (выбор триггера и набора действий, а в перспективе условия будут распространяться и на внутренние события). Разделение модалки на две разных может и облегчит логику по данным, но у нас появится ещё одна модалка, на 70% дублирующая другую. Так себе дополнение к и без того загруженному интерфейсу, как мне кажется. 

@bryzZz Твоё мнение?

**Comment by bryzZz** [comment]
По моему нужно сделать отдельные компоненты общих блоков(например блок добавления действий) и вставить их в разные модалки

**Comment by XidFanSan** [comment]
Поддерживаю Никиту

**Comment by chekoopa** [comment]
Я не против вынести компоненты в отдельные классы, но использование отдельных модалок меня беспокоит, это будет уже седьмое модальное окно. С другой стороны, если оно будет также прятаться за тернарным оператором... 

Попробуйте тогда и проверьте по производительности.

**Comment by chekoopa** [comment]
Процесс пошёл, вынесли компоненты в хуки. Пока выглядит адекватно.

**Comment by chekoopa** [comment]
Компоненты вынесены в хуки, процесс пошёл. Дальше только дорабатывать и совершенствовать.
