### ISSUE TITLE
Отображение текущих адресов для модулей загрузчика, компилятора, док-сервера

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#154]
На данный момент пользователь не может узнать адрес, подключаемого модуля через интерфейс приложения

**Comment by chekoopa** [comment]
Частично реализовано в #178. Нужно допроверить и доработать UX модалок.

**Comment by Roundabout1** [comment]
При открытии одной из этих модалок отображается текущий адрес в поле ввода. В случае загрузчика дополнительно указывается является ли текущий адрес локальным или удалённым.
