### ISSUE TITLE
Баг с историей изменений.

### ISSUE THREAD

**Issue by XidFanSan** [kruzhok-team/lapki-client#179]
1) Создаем новое событие в состоянии;
2) Удаляем это состояние;
3) Отменяем последнее действие(удаление);
4) В результате он либо показывает лишь одно событие(без действия), либо не показывает вообще что там было создано какое-либо действие.

**Comment by XidFanSan** [comment]
https://github.com/kruzhok-team/lapki-client/assets/135246322/960cb856-a9b9-4438-863c-0beb09098d35

**Comment by bryzZz** [comment]
Я что только не делал, но не могу повторить @XidFanSan

**Comment by chekoopa** [comment]
Баг не воспроизводится, скорее всего, он пофикшен.
