### ISSUE TITLE
Изменения настроек

### ISSUE THREAD

**Issue by bryzZz** [kruzhok-team/lapki-client#197]
Сейчас неудобно то что каждую настройку нужно получать асинхронно. Предлагаю сделать отдельный модуль в renderer через который можно будет синхронно управлять настройками.
Что должен делать такой модуль:
- Подгружать все настройки во время загрузки приложения
- Давать возможность получить эти настройки в любом месте
- Ререндерить компонент если у него изменились настройки

**Comment by chekoopa** [comment]
Да, самого асинхронность раздражает.
