### ISSUE TITLE
Предупреждение о неправильном наименовании компонента

### ISSUE THREAD

**Issue by L140-beep** [kruzhok-team/lapki-client#237]
Сделать всплывающее предупреждение, если пользователь называет компонент как название класса компонента (не знаю, надо ли делать то же самое для ключевых слов). Список классов предоставлю.

**Comment by chekoopa** [comment]
Там история очень интересная выходит, ведь действительно, есть список стоп-слов по типам, стоп-слов по компонентам самой платформы, стоп-слова по ключевым словам языка... Но можно начать с названий типов. Синглтоны мы исключаем из этой проверки, а остальные типы можно собрать автоматически.

**Comment by Roundabout1** [comment]
@L140-beep я сейчас работают над [валидацией имени компонента](https://github.com/kruzhok-team/lapki-client/pull/340), там уже есть проверка по ключевым словам языка C. Можешь предоставить список классов (и может других слов, которые нельзя использовать)?

**Comment by L140-beep** [comment]
> @L140-beep я сейчас работают над [валидацией имени компонента](https://github.com/kruzhok-team/lapki-client/pull/340), там уже есть проверка по ключевым словам языка C. Можешь предоставить список классов (и может других слов, которые нельзя использовать)?

Большая часть классов зависит от используемой платформы, поэтому динамически бери оттуда. Я сейчас в офис приеду, составлю список классов фреймворка.
