### ISSUE TITLE
Сохранять имя состояния сразу при клике снаружи

### ISSUE THREAD

**Issue by L140-beep** [kruzhok-team/lapki-client#248]
Сказали, что нажатие на enter для переименовывания - это неудобно.

скорее всего после ввода чтобы сразу переименовывалось (необязательно нажатие энтер)
Либо чтобы из прога режима редактирования не выходила до момента пока не нажмёшь ентер, так логичнее
Типо чтобы точно сохранить, заблочить любое взаимодействие со схемой, до нажатия ентер

**Comment by chekoopa** [comment]
Предлагаю сохранять при нажатии Enter и клике снаружи, а отменять нажатием Esc.
