### ISSUE TITLE
Уведомление об отсутствии avrdude

### ISSUE THREAD

**Issue by L140-beep** [kruzhok-team/lapki-client#249]
Думаю, стоит выводить уведомление, если avrdude не установлен, И давать ссылку с подробеой инструкцией как скачать и установить.

**Comment by Roundabout1** [comment]
работа над этим в процессе: https://github.com/kruzhok-team/lapki-client/pull/251

**Comment by XidFanSan** [comment]
Может закроем этот issues?)
