### ISSUE TITLE
Невозможно добавить заметку после импорта Берлоговской схемы

### ISSUE THREAD

**Issue by L140-beep** [kruzhok-team/lapki-client#255]
[Screencast from 09.04.2024 12:14:22.webm](https://github.com/kruzhok-team/lapki-client/assets/70793854/6f868038-8511-4adb-a987-15ace4f8a710)
Тестировалось на билде, версия билда: [19cf1bb](https://github.com/kruzhok-team/lapki-client/commit/19cf1bb64f28a2404fa0b5cf2c2d9d141079e30b)

**Comment by chekoopa** [comment]
Надо проверить на dev-версии с открытой консолью.

**Comment by L140-beep** [comment]
Не актуально
