### ISSUE TITLE
При открытии какой-либо схемы поверх редактируемой, не появляется окно запрашивающее сохранить изменения.

### ISSUE THREAD

**Issue by XidFanSan** [kruzhok-team/lapki-client#257]
При открытии какой-либо схемы поверх редактируемой не появляется окно запрашивающее сохранить изменения.

P.s. Но если поверх редактируемой схемы создавать совершенно новую, то появиться запрос на сохранение изменений.

**Comment by Roundabout1** [comment]
> Но если поверх редактируемой схемы создавать совершенно новую, то появиться запрос на сохранение изменений.
На данный момент запрос на сохранение не появляется
