### ISSUE TITLE
При создании вложенной ноды двойным кликом дублируется начальное состояние

### ISSUE THREAD

**Issue by XidFanSan** [kruzhok-team/lapki-client#293]
Когда создается состояние рядом с другим, он автоматически вкладывается во внутрь другого состояния и когда это происходит у состояния внутри появляется аж два кружочка начального состояния.

https://github.com/kruzhok-team/lapki-client/assets/135246322/5e10abf7-343c-4937-966c-aa71d2f7a1e0

**Comment by chekoopa** [comment]
Подтверждаю. Если состояние появляется двойным кликом и сразу вкладывается, возникает дубликат начального состояния (в истории не регистрируется, возможно, из-за автоматического создания).  

Если создать состояние извне и штатно вложить (без автоматики), дублирования не происходит.
