### ISSUE TITLE
Дополнительная проверка на то, что сервер действительно является локальным загрузчиком перед подключением к нему

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#294]
Ситуация: локальный загрузчик, который работал на порту X, упал, после этого на порту X, начал работать другой сервер, не являющийся локальным загрузчиком. Клиент может случайно подключиться к другому серверу. Чтобы предотвратить подобный сценарий можно добавить дополнительную проверку перед подключением к локальному загрузчику.

**Comment by chekoopa** [comment]
@Roundabout1 Нужно проверить, потому что скорее всего ты это починил в #292

**Comment by Roundabout1** [comment]
Да, теперь клиент ищет новый свободный порт после нажатия на кнопку перезапуска, поэтому он не может поключиться к какому-то другому серверу по ошибке.
