### ISSUE TITLE
Отображается тёмная тема при запуске, даже если выбрана светлая

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#295]
![image](https://github.com/kruzhok-team/lapki-client/assets/86153878/1a991b75-00de-4ed9-a337-ce103b0e3dfe)
Эта проблема возникает на билде для Windows, но не на Dev-версии.  

Билд был создан на основе последней версии ветки main на момент написания issue.

Тема меняется обратно, если выбрать тёмную тему в настройках, а затем снова светлую, но при перезапуске проблема повторяется.

**Comment by Roundabout1** [comment]
На Linux такая же проблема

**Comment by chekoopa** [comment]
Другими словами, не применяется тема при запуске.
@bryzZz ?

**Comment by Roundabout1** [comment]
Да. Было проверено на билде main ветки на момент создания issue.
