### ISSUE TITLE
После выбора пункта контекстного меню не возвращается фокус в холст

### ISSUE THREAD

**Issue by captaincod** [kruzhok-team/lapki-client#312]
Если я добавляю на схему ПС выбора, то с помощью Ctrl+Z она не удаляется, можно удалить только нажав на кнопку Назад в Истории изменений. При этом, если также создать состояние сразу после создания ПС выбора, то всё удаляется даже просто с Ctrl+Z. Переключение раскладки не повлияло.

https://github.com/kruzhok-team/lapki-client/assets/46486971/d207f5db-7b1b-4db7-93fc-8afa8cbfcdbf

**Comment by chekoopa** [comment]
Воспроизвёл баг, на самом деле дело в другом немного. 

Если создать ПС выбора или конечное, холст теряет фокус, и не работает горячая клавиша Ctrl-Z (как и остальные, по сути). Если после выбора пункта нажать на холст, клавиши снова начинают работать. 

@bryzZz
