### ISSUE TITLE
Нет возможности поменять цвет стрелки начального состояния

### ISSUE THREAD

**Issue by captaincod** [kruzhok-team/lapki-client#314]
При создании новой схемы стрелка от начального состояния всегда идёт **белого** цвета. На **_светлом_** фоне. Приходится работать с тёмной темой, лишь бы стрелка "читалась" визуально. 
При этом при открытии старых схем / сохранении и открытии этой схемы стрелке задаётся, как понимаю, рандомный цвет. Это довольно весело, но если хочется сделать красивую схему - облом, иногда такие странные сочетания цветов появляются...

Только что созданная схема, светлая тема:
![image](https://github.com/kruzhok-team/lapki-client/assets/46486971/cc7c868c-c98b-4cdb-b6f7-a0c8bba998b6)

Открытая старая схема, светлая тема:
![image](https://github.com/kruzhok-team/lapki-client/assets/46486971/163a183c-3213-491f-aecd-9fad21a17337)

**Comment by chekoopa** [comment]
Закрыто в #387
