### ISSUE TITLE
Пробелы в названиях компонентов

### ISSUE THREAD

**Issue by captaincod** [kruzhok-team/lapki-client#315]
IDE никак не указывает, что нельзя создавать компонент с названием, в котором содержится пробел. Если такой создать, то либо IDE через неопределённое время крашится с ошибкой undefined, либо схема после сохранения и повторного открытия выдаёт, например, ошибки, как на скриншоте (см. переходы)

![image](https://github.com/kruzhok-team/lapki-client/assets/46486971/c80b9001-cb7e-433b-a25a-103b1deb5ec7)

Прикрепляю ссылку на схему, с которой срабатывает ошибка:
https://gist.github.com/captaincod/b46a683bb67dd82bbcf839e557e19956

**Comment by chekoopa** [comment]
Нужно либо запрещать пробелы (что логично для компонентной архитектуры, особенно в Arduino), либо как-то их обрабатывать и экранировать. Склоняюсь к первому варианту (можно в мягкой форме, заменять на подчёркивания)

**Comment by Roundabout1** [comment]
Можно закрыть issue
