### ISSUE TITLE
У условного выбора появляется пустой черный блок.

### ISSUE THREAD

**Issue by XidFanSan** [kruzhok-team/lapki-client#320]
У условного выбора появляется пустой черный блок, что портит общий вид и не понятно зачем он там вообще нужен.
Надо придумать что с этим блоком делать.
![image](https://github.com/kruzhok-team/lapki-client/assets/135246322/59c56cfa-0f24-469c-9ed0-a1eb9c45680a)

**Comment by chekoopa** [comment]
Это блок действия, просто рисуется без триггера. Пока надо просто убрать сдвиг, а потом решить, как всё же правильно делать отрисовку.
