### ISSUE TITLE
Кнопка свойства не блокируется при создании новой схемы

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#324]
При открытии IDE кнопка "свойства" заблокирована, но при создании схемы она разблокируется, это приводит к тому, что при нажатии на кнопки "свойства" открытваются, либо окно свойства с пустыми параметрами, либо окно свойства с параметрами предыдущей открытой схемы. После сохранения схемы, окно со свойствами работет корректно.

Проблему можно решить, разблокируя кнопку после того как файл со схемой будет сохранён.

**Comment by chekoopa** [comment]
Это штатно. Блокировать ничего не нужно. Нужно:
 - проверить, чтобы не показывались параметры предыдущей схемы
 - пробросить в окно те параметры, которые известны до воплощения схемы в файл (тип платформы, например)
 - проверить, сохраняются ли свойства, которые добавляются в пустую схему.
