### ISSUE TITLE
При загрузке IDE изредка может вылазить критическая ошибка

### ISSUE THREAD

**Issue by XidFanSan** [kruzhok-team/lapki-client#346]
![image](https://github.com/kruzhok-team/lapki-client/assets/135246322/0ec5329b-1c9c-4b31-bf4a-1aa64991339a)
Ошибка исчезает после перезагрузке IDE, так как возникает в хаотичном случае.

**Comment by chekoopa** [comment]
[Проблема не на нашей стороне.](https://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome) [Баг в Хромиуме.](https://issues.chromium.org/issues/41050271)

В этом смысле он проявляется только в режиме разработки с ресурсами (которые билд берёт по серверу) и в целом с локальным загрузчиком.
