### ISSUE TITLE
Не работает импорт в IDE.

### ISSUE THREAD

**Issue by XidFanSan** [kruzhok-team/lapki-client#356]
![image](https://github.com/kruzhok-team/lapki-client/assets/135246322/482cd49e-0448-4a8c-b6ff-926f7ef3026d)

**Comment by chekoopa** [comment]
Не воспроизвёл на актуальном мастере. Какой хэш коммита, какой файл загружал?

Возможно, снова беды с кэшем на твоей стороне.
