### ISSUE TITLE
Avrdude теряется из виду при сбросе настроек

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#402]
Если сбросить настройки, то IDE "теряет" avrdude и отправляет клиенту уведомление о том, что этой программы нет, даже если она установлена. Это уведомление пропадает при повторном запуске IDE, но не при перезагрузке (ctrl + r).

**Comment by Roundabout1** [comment]
https://github.com/kruzhok-team/lapki-client/pull/404

**Comment by chekoopa** [comment]
Закрыто в #404
