### ISSUE TITLE
Компонент AnalogIn не может использовать аналоговые пины

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#436]
> Для считывания аналогового сигнала, принимающего широкий спектр значений, а не просто 0 или 1, как цифровой, подходят только порты, помеченные на плате как «ANALOG IN» и пронумерованные с префиксом A. Для Arduino Uno — это A0-A5.

[Светильник с управляемой яркостью](https://wiki.amperka.ru/%D0%BA%D0%BE%D0%BD%D1%81%D0%BF%D0%B5%D0%BA%D1%82-arduino:%D1%81%D0%B2%D0%B5%D1%82%D0%B8%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA-%D1%81-%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D0%BC%D0%BE%D0%B9-%D1%8F%D1%80%D0%BA%D0%BE%D1%81%D1%82%D1%8C%D1%8E)

**Comment by chekoopa** [comment]
Это к слову о «перечисляемых» параметрах, значения которых задаются списком.

#437
