### ISSUE TITLE
Падение IDE при попытке загрузить схему или что-либо сделать в ней

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#443]
Иногда при работе со схемой, IDE внезапно падает. При этом загрузка такой схемы может обернуться новым крашем, несмотря на то, что раньше схема загружалась нромально. Возможно, что схема "портиться" из-за какого-то бага, что не позволяет её загрузить повторно. Были попытки перезагрузить как IDE, так и ноутбук, но ничего не помогло. 
Текст ошибки из консоли и сама схема приведены в архиве: 
[Испорченная схема.zip](https://github.com/user-attachments/files/16906071/default.zip)

**Comment by L140-beep** [comment]
Если поменять название состояния с "8" на буквенное, то все будет работать
