### ISSUE TITLE
В текстовом режиме схема не компилируется, если присутствует знак деления '/'

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#543]
- Пример: `PWM1.write(AnalogIn3.value / 4);`
- Другие арифметические знаки работают. 
- Компилятор не даёт никакого вывода, он просто отключает клиент.
- Схема (машина состояния 3-test): [multi.zip](https://github.com/user-attachments/files/17957297/multi.zip)
![image](https://github.com/user-attachments/assets/98b5066c-2c45-4928-9bd8-0ae07b67e090)

**Comment by chekoopa** [comment]
Видимо, некорректно срабатывает дробление на события. Надо смотреть в самом компиляторе.
