### ISSUE TITLE
Не загораются некоторые светодиоды в методе setPattern

### ISSUE THREAD

**Issue by L140-beep** [kruzhok-team/lapki-client#549]

**Comment by chekoopa** [comment]
Убедитесь, что это не баг конкретного устройства. Если нет, может быть проблема с инициализацией пинов в самой прошивке.

**Comment by L140-beep** [comment]
@chekoopa У нас есть еще одна матрица?

**Comment by chekoopa** [comment]
> У нас есть еще одна матрица?

Спроси в чате у Широкова.
