### ISSUE TITLE
Не компилируются схемы, содержащие 3 и более переходов с условиями из одного состояния 

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#593]
Клиент отсоединяется от компилятора со статусом NOTOK, журнал компиляции и код не доступны.

Пример схемы, если удалить один из переходов, то схема скомпилируется
![image](https://github.com/user-attachments/assets/d5176c0b-ae5b-41ce-91e7-ca3b7ecb47d8)

**Comment by L140-beep** [comment]
Закрыто в https://github.com/kruzhok-team/lapki-compiler/pull/86
