### ISSUE TITLE
Порядок отрисовки нод

### ISSUE THREAD

**Issue by bryzZz** [kruzhok-team/lapki-client#61]
Сейчас ноды отрисовываются в порядке перечисления. Нужно сделать так, чтобы этот порядок можно было менять.
При нажатии на состояние или связь делать его поверх остальных.
![Screenshot from 2023-10-19 20-35-26](https://github.com/kruzhok-team/lapki-client/assets/73271787/86cf1f21-899a-4504-a629-00c1147a2f2c)

**Comment by bryzZz** [comment]
Вариант схемы со слоями:
![Screenshot from 2023-10-20 11-57-26](https://github.com/kruzhok-team/lapki-client/assets/73271787/48d3df6b-f47b-4155-8124-eaa7bfc9c117)

Этот вариант рабочий но у него есть одна проблема. Допустим у нас есть две ноды, при выделении первой она переместилась на второй слой и стала поверх второй ноды. Что делать при выделении второй ноды? Перемещать на третий слой? Или перемещать первую ноду обратно на первый слой а вторую на второй?

Тут хотелось бы какое-нибудь поведение массива, чтобы выделенная нода перемещалась в конец и рисовалась последней(то есть самой верхней). Этот вариант сделать не получается потому что в системы есть очень много операций чтения и не хотелось бы терять сложность O(1). Ещё в таком варианте не понятно как сохранить эту последовательность при перезагрузке, в первом варианте в схему можно просто добавить слои.

Есть идея ввести кэш порядка отрисовки, чтобы он был массовом айдишников и реагировал на изменения объекта с нодами чтобы изменится самому. Тогда во время отрисовки нужно будет итерироваться по кэшу и выдёргивать ноды по айдишнику. Ещё лучше чтобы кэш был связным списком, тогда при перемещении ноды в конец не нужно создавать новый массов

**Comment by chekoopa** [comment]
По-хорошему, «слои» есть как минимум в пределах дочерних контейнеров. Кажется, наиболее понятной историей здесь будет порядок «вложенность – z-order – идентификатор». То есть дочерние ноды имеют базовую вложенность, как у своей родительской ноды, в её пределах смотрим на z-order (условно, номер слоя), при одинаковом z-order смотрим на id-шник. 

Другой вопрос, как это с инженерной стороны реализовать. Возможно, стоит пошариться по похожим решениям и посмотреть, как сделано у них.
