### ISSUE TITLE
Неинициализированный пин ReDe вешает пользовательскую шину

### ISSUE THREAD

**Issue by regellosigkeitsaxiom** [kruzhok-team/lapki-client#618]
Если этот пин не инициализировать и бросить, то трансивер пользовательской шины включается в режим передачи (при условии, что киберген передачу разрешает, а он по-умолчанию разрешает) и вешает всю пользовательскую шину.
Чтобы этого не было, этот пин должен быть инициализирован всегда, даже если конкретный модуль пользовательскую шину не использует.
Параметры инициализации: Open-drain (OD), прижать к земле.

**Comment by CodeR-na-r1** [comment]
В прошивке пользователя пин уже инициализируется (https://github.com/kruzhok-team/lapki-compiler/commit/19de6df6783795d6eff56f9ed2a27f4bad33f5f1)
Есть возможность инициализировать пин из загрузчика, сказав кибергену?

**Comment by regellosigkeitsaxiom** [comment]
Нет, такой возможности нет, Будем думать над аппаратным решением в будущих платах.
