### ISSUE TITLE
Нужно сбрасывать инициализацию модулей, использованных загрузчиком.

### ISSUE THREAD

**Issue by regellosigkeitsaxiom** [kruzhok-team/lapki-client#620]
Загрузчик не «прибирает за собой», и попытке использования модулей, которые он уже настроил, можно натолкнуться на о-о-о-очень странные по симптомам баги. Для полной реинициализации модуля обычно достаточно включить и на следующем такте выключить соответствующий модулю бит в каком-то из регистров *RSTR.
Навскидку, затронутые модули (список неполон/неточен, нужно проверять по коду):
- GPIOA
- GPIOB
- DMA1
- USART1
- Настройки тактовой частоты

**Comment by CodeR-na-r1** [comment]
Правки внесены (https://github.com/kruzhok-team/lapki-compiler/commit/f4aea34531d0bf8455c101600da4f8ee6aafc1bb)
