### ISSUE TITLE
При смене на светлую тему, модальные окна остаются тёмными

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#96]
![изображение](https://github.com/kruzhok-team/lapki-client/assets/86153878/28504d02-367f-4f67-8777-82f97fb61853)

**Comment by chekoopa** [comment]
Да, в EventsModal не применяется тема (хардкод). Вдобавок к этому плохо ведут себя текстовые поля.

![Скриншот бага](https://github.com/kruzhok-team/lapki-client/assets/1689801/1f9652ac-4e06-46b9-8a47-d833c176bc37)

Это **критический баг** интерфейса.
